#!/usr/bin/env bash
# Script that configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Replace or add localhost and facebook.com entries
sed -i 's/127.0.0.1[[:space:]]*localhost/127.0.0.2\tlocalhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
