#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.bak

sed -i '/127.0.0.1\s\+localhost/s/^/#/' /etc/hosts
echo "127.0.0.2 localhost" | tee -a /etc/hosts

sed -i '/facebook.com/s/^/#/' /etc/hosts 
echo "8.8.8.8 facebook.com" | tee -a /etc/hosts

echo "Configuration complete. /etc/hosts has been updated."
