#!/usr/bin/env bash
# listens on port 98 on localhost.

# Port to listen on
PORT=98

# Listen on localhost and port 98
echo "Listening on localhost:$PORT..."

# Use netcat to listen on the specified port and handle telnet connections
while true; do
  nc -l 127.0.0.1 $PORT | telnet
done
